### ISSUE TITLE
java.io.IOException: No FileSystem for scheme: swift2d

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#29]
A new error is occuring:

``````
16:55:14.756 [QUIET] [system.out] bicluster#4|  File "/home/biadmin/test-1460994838127/exporttoswift.py", line 50, in <module>
16:55:14.757 [QUIET] [system.out] bicluster#4|    distData.saveAsTextFile("swift2d://{0}.{1}/one1.txt".format(container, service_name))
16:55:14.757 [QUIET] [system.out] bicluster#4|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1508, in saveAsTextFile
16:55:14.757 [QUIET] [system.out] bicluster#4|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
16:55:14.758 [QUIET] [system.out] bicluster#4|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
16:55:14.807 [QUIET] [system.out] bicluster#4|py4j.protocol.Py4JJavaError: An error occurred while calling o52.saveAsTextFile.
16:55:14.807 [QUIET] [system.out] bicluster#4|: java.io.IOException: No FileSystem for scheme: swift2d
16:55:14.807 [QUIET] [system.out] bicluster#4|  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2644)
16:55:14.807 [QUIET] [system.out] bicluster#4|  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2651)
16:55:14.807 [QUIET] [system.out] bicluster#4|  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
16:55:14.808 [QUIET] [system.out] bicluster#4|  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
16:55:14.808 [QUIET] [system.out] bicluster#4|  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
16:55:14.808 [QUIET] [system.out] bicluster#4|  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
16:55:14.808 [QUIET] [system.out] bicluster#4|  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
16:55:14.809 [QUIET] [system.out] bicluster#4|  at org.apache.spark.SparkHadoopWriter$.createPathFromString(SparkHadoopWriter.scala:170)
16:55:14.809 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:988)
16:55:14.809 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
16:55:14.809 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
16:55:14.810 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
16:55:14.810 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
16:55:14.810 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
16:55:14.810 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:965)
16:55:14.810 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:897)
16:55:14.810 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
16:55:14.810 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
16:55:14.811 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
16:55:14.811 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
16:55:14.811 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
16:55:14.811 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:896)
16:55:14.811 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1426)
16:55:14.811 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
16:55:14.812 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
16:55:14.812 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
16:55:14.812 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
16:55:14.812 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
16:55:14.812 [QUIET] [system.out] bicluster#4|  at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1405)
16:55:14.812 [QUIET] [system.out] bicluster#4|  at org.apache.spark.api.java.JavaRDDLike$class.saveAsTextFile(JavaRDDLike.scala:522)
16:55:14.813 [QUIET] [system.out] bicluster#4|  at org.apache.spark.api.java.AbstractJavaRDDLike.saveAsTextFile(JavaRDDLike.scala:47)
16:55:14.813 [QUIET] [system.out] bicluster#4|  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:55:14.813 [QUIET] [system.out] bicluster#4|  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
16:55:14.813 [QUIET] [system.out] bicluster#4|  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:55:14.813 [QUIET] [system.out] bicluster#4|  at java.lang.reflect.Method.invoke(Method.java:606)
16:55:14.813 [QUIET] [system.out] bicluster#4|  at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
16:55:14.814 [QUIET] [system.out] bicluster#4|  at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
16:55:14.814 [QUIET] [system.out] bicluster#4|  at py4j.Gateway.invoke(Gateway.java:259)
16:55:14.814 [QUIET] [system.out] bicluster#4|  at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
16:55:14.814 [QUIET] [system.out] bicluster#4|  at py4j.commands.CallCommand.execute(CallCommand.java:79)
16:55:14.814 [QUIET] [system.out] bicluster#4|  at py4j.GatewayConnection.run(GatewayConnection.java:207)
16:55:14.814 [QUIET] [system.out] bicluster#4|  at java.lang.Thread.run(Thread.java:745)```
``````
- python spark code is here: [exporttoswift.py](https://github.com/snowch/biginsight-examples/blob/master/examples/SwiftPushWithSpark/exporttoswift.py)
- gradle build file (executes python code on cluster over ssh): [build.gradle](https://github.com/snowch/biginsight-examples/blob/master/examples/SwiftPushWithSpark/build.gradle)

**Comment by snowch** [comment]
@gilv - I have maybe hit another user error?  I have provided a link to the code at the bottom of the issue.

**Comment by gilv** [comment]
@snowch 
If it helps you this is how i am using it with python (to access SL object store )

import pprint
import os
from pyspark.sql import SQLContext
from pyspark import SparkContext, SparkConf
from pyspark.sql.types import *

conf = SparkConf().setAppName("TEST")

sc = SparkContext(conf=conf)

sc._jsc.hadoopConfiguration().set("fs.swift2d.impl","com.ibm.stocator.fs.ObjectStoreFileSystem")
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".auth.url",authurl)
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".public","true")
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".tenant",tenant)
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".password",apikey)
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".username",username)
sc._jsc.hadoopConfiguration().set("fs.swift2d.service."+datacenter+".auth.method","swiftauth")

sqlContext = SQLContext(sc)

......

**Comment by gilv** [comment]
@snowch 
You have to add
sc._jsc.hadoopConfiguration().set("fs.swift2d.impl","com.ibm.stocator.fs.ObjectStoreFileSystem")

**Comment by gilv** [comment]
@snowch does it helps? is it working now?

**Comment by snowch** [comment]
@gilv useful thanks, it has got me further.  

I now have:

```
17:45:07.955 [ERROR] [system.err] bicluster#7|16/04/18 16:45:07 INFO impl.ClientImpl: JOSS / Attempting authentication with tenant name: null, tenant ID: null, username: null, Auth URL: https://identity.open.softlayer.com/v3/auth/tokens
17:45:08.513 [ERROR] [system.err] bicluster#7|16/04/18 16:45:08 INFO impl.ClientImpl: JOSS / Successfully authenticated
17:45:08.542 [QUIET] [system.out] bicluster#7|Traceback (most recent call last):
17:45:08.542 [QUIET] [system.out] bicluster#7|  File "/home/biadmin/test-1460997828502/exporttoswift.py", line 62, in <module>
17:45:08.543 [QUIET] [system.out] bicluster#7|    counts.saveAsTextFile("swift2d://{0}.{1}/counts.txt".format(container, service_name))
17:45:08.543 [QUIET] [system.out] bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1508, in saveAsTextFile
17:45:08.543 [QUIET] [system.out] bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
17:45:08.543 [QUIET] [system.out] bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
17:45:08.544 [QUIET] [system.out] bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
17:45:08.568 [QUIET] [system.out] bicluster#7|py4j.protocol.Py4JJavaError: An error occurred while calling o65.saveAsTextFile.
17:45:08.569 [QUIET] [system.out] bicluster#7|: java.lang.NullPointerException
17:45:08.569 [QUIET] [system.out] bicluster#7|  at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:100)
17:45:08.570 [QUIET] [system.out] bicluster#7|  at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
17:45:08.570 [QUIET] [system.out] bicluster#7|  at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35)
```

I'll dump out the parameter values to see if they are null.

**Comment by gilv** [comment]
@snowch here is the solution :) i see you use Bluemix..

The value of fs.swift2d.service.SERVICE_NAME.username should container USERID from VCAP service.

The value of fs.swift2d.service.SERVICE_NAME.tenant should contain PROJECT ID

The auth method may be skipped, as Keystone v3 is default.
Also region may be skipped. Dallas is default.

**Comment by snowch** [comment]
@gilv Still failing for me ...

```
18:24:17.975 [QUIET] [system.out] bicluster#7|********************************************************************************
18:24:17.976 [QUIET] [system.out] bicluster#7|swift2d://1461000175065.dallas/counts.txt
18:24:17.976 [QUIET] [system.out] bicluster#7|********************************************************************************
18:24:18.014 [ERROR] [system.err] bicluster#7|16/04/18 17:24:17 INFO impl.ClientImpl: JOSS / Creating real account instance
18:24:18.015 [ERROR] [system.err] bicluster#7|16/04/18 17:24:17 INFO impl.ClientImpl: JOSS / * Allow caching: true
18:24:18.029 [ERROR] [system.err] bicluster#7|16/04/18 17:24:17 INFO impl.ClientImpl: JOSS / Attempting authentication with tenant name: null, tenant ID: null, username: null, Auth URL: https://identity.open.softlayer.com/v3/auth/tokens
18:24:18.984 [ERROR] [system.err] bicluster#7|16/04/18 17:24:18 INFO impl.ClientImpl: JOSS / Successfully authenticated
18:24:18.985 [ERROR] [system.err] bicluster#7|16/04/18 17:24:18 INFO impl.ClientImpl: JOSS / Applying preferred region: dallas
18:24:18.987 [ERROR] [system.err] bicluster#7|16/04/18 17:24:18 INFO impl.ClientImpl: JOSS / Using TempURL hash prefix source: PUBLIC_URL_PATH
18:24:20.374 [ERROR] [system.err] bicluster#7|16/04/18 17:24:19 INFO core.ServerTime: JOSS / Server time is Mon, 18 Apr 2016 17:24:19 GMT
18:24:20.375 [ERROR] [system.err] bicluster#7|16/04/18 17:24:19 INFO core.ServerTime: JOSS / Local time is Mon, 18 Apr 2016 17:24:19 GMT
18:24:20.375 [ERROR] [system.err] bicluster#7|16/04/18 17:24:19 INFO core.ServerTime: JOSS / Local time modifier in milliseconds: -561
18:24:20.389 [ERROR] [system.err] bicluster#7|16/04/18 17:24:19 INFO core.AbstractAccount: JOSS / Use public host: null
18:24:20.390 [ERROR] [system.err] bicluster#7|16/04/18 17:24:19 INFO core.AbstractAccount: JOSS / Use private host: null
18:24:20.390 [ERROR] [system.err] bicluster#7|16/04/18 17:24:19 INFO core.AbstractAccount: JOSS / Allow Container caching: true
18:24:20.538 [ERROR] [system.err] bicluster#7|16/04/18 17:24:19 INFO core.AbstractAccount: JOSS / Allow reauthentication: true
18:24:20.538 [ERROR] [system.err] bicluster#7|16/04/18 17:24:19 INFO core.AbstractAccount: JOSS / Setting hash password
18:24:20.864 [QUIET] [system.out] bicluster#7|Traceback (most recent call last):
18:24:20.864 [QUIET] [system.out] bicluster#7|  File "/home/biadmin/test-1461000175065/exporttoswift.py", line 73, in <module>
18:24:20.864 [QUIET] [system.out] bicluster#7|    counts.saveAsTextFile(swift_file_url)
18:24:20.864 [QUIET] [system.out] bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1508, in saveAsTextFile
18:24:20.871 [QUIET] [system.out] bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
18:24:20.871 [QUIET] [system.out] bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
18:24:20.872 [QUIET] [system.out] bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
18:24:21.026 [QUIET] [system.out] bicluster#7|py4j.protocol.Py4JJavaError: An error occurred while calling o86.saveAsTextFile.
18:24:21.026 [QUIET] [system.out] bicluster#7|: java.lang.NullPointerException
18:24:21.026 [QUIET] [system.out] bicluster#7|  at org.apache.hadoop.security.SecurityUtil.buildDTServiceName(SecurityUtil.java:257)
18:24:21.026 [QUIET] [system.out] bicluster#7|  at org.apache.hadoop.fs.FileSystem.getCanonicalServiceName(FileSystem.java:302)
18:24:21.026 [QUIET] [system.out] bicluster#7|  at org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:524)
18:24:21.027 [QUIET] [system.out] bicluster#7|  at org.apache.hadoop.fs.FileSystem.addDelegationTokens(FileSystem.java:508)
18:24:21.027 [QUIET] [system.out] bicluster#7|  at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:121)
18:24:21.027 [QUIET] [system.out] bicluster#7|  at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:100)
18:24:21.027 [QUIET] [system.out] bicluster#7|  at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodes(TokenCache.java:80)
18:24:21.027 [QUIET] [system.out] bicluster#7|  at org.apache.hadoop.mapred.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:126)
18:24:21.027 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1089)
18:24:21.028 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
18:24:21.028 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
18:24:21.028 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
18:24:21.028 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
18:24:21.028 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
18:24:21.028 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1065)
18:24:21.028 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:989)
18:24:21.028 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
18:24:21.029 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
18:24:21.029 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
18:24:21.029 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
18:24:21.029 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
18:24:21.029 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:965)
18:24:21.029 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:897)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:896)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1426)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
18:24:21.030 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
18:24:21.031 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
18:24:21.119 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
18:24:21.120 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
18:24:21.120 [QUIET] [system.out] bicluster#7|  at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1405)
18:24:21.120 [QUIET] [system.out] bicluster#7|  at org.apache.spark.api.java.JavaRDDLike$class.saveAsTextFile(JavaRDDLike.scala:522)
18:24:21.120 [QUIET] [system.out] bicluster#7|  at org.apache.spark.api.java.AbstractJavaRDDLike.saveAsTextFile(JavaRDDLike.scala:47)
18:24:21.120 [QUIET] [system.out] bicluster#7|  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:24:21.121 [QUIET] [system.out] bicluster#7|  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:24:21.121 [QUIET] [system.out] bicluster#7|  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:24:21.121 [QUIET] [system.out] bicluster#7|  at java.lang.reflect.Method.invoke(Method.java:497)
18:24:21.121 [QUIET] [system.out] bicluster#7|  at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
18:24:21.121 [QUIET] [system.out] bicluster#7|  at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
18:24:21.121 [QUIET] [system.out] bicluster#7|  at py4j.Gateway.invoke(Gateway.java:259)
18:24:21.122 [QUIET] [system.out] bicluster#7|  at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
18:24:21.122 [QUIET] [system.out] bicluster#7|  at py4j.commands.CallCommand.execute(CallCommand.java:79)
18:24:21.122 [QUIET] [system.out] bicluster#7|  at py4j.GatewayConnection.run(GatewayConnection.java:207)
18:24:21.122 [QUIET] [system.out] bicluster#7|  at java.lang.Thread.run(Thread.java:745)
```

The swift file url is: 

```
swift2d://1461000175065.dallas/counts.txt
```

My latest code is pushed to the repo.

**Comment by snowch** [comment]
@gilv will the library create the container if it doesn't exist already?

**Comment by gilv** [comment]
@snowch it will

**Comment by gilv** [comment]
@snowch the service_name in your configuration is dallas?

**Comment by snowch** [comment]
@gilv yes, it is set to dallas.

**Comment by snowch** [comment]
@gilv I have a properties file for the biginsights cluster hostname, object store details, etc.

Interestingly, the code works on 'Basic' BigInsight clusters, but not 'Standard' ones.

**Comment by snowch** [comment]
Closing this - I'll open a new ticket for an issue running on one type of cluster yet running ok on another type.
