### ISSUE TITLE
SparkObjectStoreIntegration - runs ok on Basic cluster, fails on Standard cluster

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#31]
Here is the stacktrace on the Standard cluster:

```
bicluster#7|Traceback (most recent call last):
bicluster#7|  File "/home/biadmin/test-1461009081582/exporttoswift.py", line 73, in <module>
bicluster#7|    counts.saveAsTextFile(swift_file_url)
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1508, in saveAsTextFile
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 36, in deco
bicluster#7|  File "/usr/iop/4.1.0.0/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
bicluster#7|py4j.protocol.Py4JJavaError: An error occurred while calling o86.saveAsTextFile.
bicluster#7|: java.lang.NullPointerException
bicluster#7|    at org.apache.hadoop.security.SecurityUtil.buildDTServiceName(SecurityUtil.java:257)
bicluster#7|    at org.apache.hadoop.fs.FileSystem.getCanonicalServiceName(FileSystem.java:302)
bicluster#7|    at org.apache.hadoop.fs.FileSystem.collectDelegationTokens(FileSystem.java:524)
bicluster#7|    at org.apache.hadoop.fs.FileSystem.addDelegationTokens(FileSystem.java:508)
bicluster#7|    at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:121)
bicluster#7|    at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodesInternal(TokenCache.java:100)
bicluster#7|    at org.apache.hadoop.mapreduce.security.TokenCache.obtainTokensForNamenodes(TokenCache.java:80)
bicluster#7|    at org.apache.hadoop.mapred.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:126)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1089)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
bicluster#7|    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1065)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:989)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
bicluster#7|    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:965)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:897)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
bicluster#7|    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
bicluster#7|    at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:896)
bicluster#7|    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1426)
bicluster#7|    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
bicluster#7|    at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
bicluster#7|    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
bicluster#7|    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
bicluster#7|    at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1405)
bicluster#7|    at org.apache.spark.api.java.JavaRDDLike$class.saveAsTextFile(JavaRDDLike.scala:522)
bicluster#7|    at org.apache.spark.api.java.AbstractJavaRDDLike.saveAsTextFile(JavaRDDLike.scala:47)
bicluster#7|    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
bicluster#7|    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
bicluster#7|    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
bicluster#7|    at java.lang.reflect.Method.invoke(Method.java:497)
bicluster#7|    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
bicluster#7|    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
bicluster#7|    at py4j.Gateway.invoke(Gateway.java:259)
bicluster#7|    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
bicluster#7|    at py4j.commands.CallCommand.execute(CallCommand.java:79)
bicluster#7|    at py4j.GatewayConnection.run(GatewayConnection.java:207)
bicluster#7|    at java.lang.Thread.run(Thread.java:745)
```

**Comment by snowch** [comment]
I checked in swift and noticed the folder was created, but the files were not added when I had the above error.   @gilv - any ideas?

**Comment by pregazzoni** [comment]
Repro same error as Chris on my cluster (I used same swift credentials).

**Comment by snowch** [comment]
Similarly, I tested against another Basic cluster and it worked ok.

**Comment by gilv** [comment]
@snowch what is Basic and Standard cluster means?

**Comment by snowch** [comment]
@gilv  - These are the different offerings of BigInsights on Bluemix:
- Basic = Basic
- Standard = Enterprise

![screen shot 2016-04-18 at 22 06 16](https://cloud.githubusercontent.com/assets/147713/14619921/ea5d7260-05b1-11e6-8a35-401b23bf9d7e.png)

Both types appear to be running Spark 1.5.1 on top of BigInsights 4.1.0.0.

**Comment by gilv** [comment]
@snowch What are the steps to reproduce this error? I can gladly debug it

**Comment by snowch** [comment]
@gilv do you have access to a BigInsights 4.1.0.0 cluster?  If not, I can probably give you credentials for one.

**Comment by gilv** [comment]
@snowch I don't. I never tried it with BigInsights cluster. I see the code lines where it fails with Nullpointer, but i need to debug it. I don't really know what is wrong until i run it. It seems very easy to debug.
Please provide me a way to run the same so i can get the same exception.

**Comment by snowch** [comment]
@gilv I'm waiting for confirmation that I can share the standard cluster credentials with you.  After that, you will need to follow the setup process outlined here:  https://github.com/snowch/biginsight-examples#setup-instructions (should take about 5 minutes to setup).

**Comment by snowch** [comment]
Upstream bug reference https://github.com/SparkTC/stocator/issues/33

**Comment by snowch** [comment]
Fixed by: https://github.com/snowch/biginsight-examples/commit/ed274069c6c7cb9fe2c3014070814a010b5b351e
