### ISSUE TITLE
DashDBPullWithBigSQL - fails with SQLCODE=-5105, SQLSTATE=58040, SQLERRMC=SCHEDULER;FRONT-END;[SCL-0-43ab63155], DRIVER=3.70.4

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#39]
```
snowch$ ../../gradlew Example
:CreateTrustStore
Certificate was added to keystore
:SetupLibs
:compileJava UP-TO-DATE
:compileGroovy
:processResources UP-TO-DATE
:classes
:Load
Drop table
Create table
Load into table from dashdb
Select from table: select language_code, language_desc from test_1461273814944
Apr 21, 2016 10:25:00 PM groovy.sql.Sql eachRow
WARNING: Failed to execute: select language_code, language_desc from test_1461273814944 because: DB2 SQL Error: SQLCODE=-5105, SQLSTATE=58040, SQLERRMC=SCHEDULER;FRONT-END;[SCL-0-43ab63155], DRIVER=3.70.4
Exception in thread "main" com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-5105, SQLSTATE=58040, SQLERRMC=SCHEDULER;FRONT-END;[SCL-0-43ab63155], DRIVER=3.70.4
    at com.ibm.db2.jcc.am.gd.a(Unknown Source)
    at com.ibm.db2.jcc.am.gd.a(Unknown Source)
    at com.ibm.db2.jcc.am.gd.a(Unknown Source)
    at com.ibm.db2.jcc.am.yo.c(Unknown Source)
    at com.ibm.db2.jcc.am.yo.d(Unknown Source)
    at com.ibm.db2.jcc.am.yo.a(Unknown Source)
    at com.ibm.db2.jcc.t4.bb.h(Unknown Source)
    at com.ibm.db2.jcc.t4.bb.b(Unknown Source)
    at com.ibm.db2.jcc.t4.p.a(Unknown Source)
    at com.ibm.db2.jcc.t4.vb.i(Unknown Source)
    at com.ibm.db2.jcc.am.yo.ib(Unknown Source)
    at com.ibm.db2.jcc.am.yo.a(Unknown Source)
    at com.ibm.db2.jcc.am.yo.a(Unknown Source)
    at com.ibm.db2.jcc.am.yo.executeQuery(Unknown Source)
    at groovy.sql.Sql.eachRow(Sql.java:1178)
    at groovy.sql.Sql.eachRow(Sql.java:1143)
    at groovy.sql.Sql.eachRow(Sql.java:1082)
    at groovy.sql.Sql$eachRow.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at Load.run(Load.groovy:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
    at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:407)
    at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at Load.main(Load.groovy)
:Load FAILED
```

**Comment by snowch** [comment]
The resolution was to restart the BigSQL service from Ambari (Restart All).
