### ISSUE TITLE
BigSqlGroovy query HDFS example - (external hadoop table)

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#63]
Create an example for querying HDFS data without having to load it.

**Comment by snowch** [comment]
```
:QueryHdfs
Drop table
Copy data to tmp
log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.PoolingClientConnectionManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Create table
May 04, 2016 9:31:51 AM groovy.sql.Sql execute
WARNING: Failed to execute:
  create external hadoop table if not exists test_1462350709768 (id int, name varchar(30))
  row format delimited
  fields terminated by '|'
  lines terminated by '\n'
  location '/tmp/data.csv'
 because: DB2 SQL Error: SQLCODE=-5105, SQLSTATE=58040, SQLERRMC=;HIVE;[BSL-0-47ae504cb], DRIVER=3.70.4
Exception in thread "main" com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-5105, SQLSTATE=58040, SQLERRMC=;HIVE;[BSL-0-47ae504cb], DRIVER=3.70.4
    at com.ibm.db2.jcc.am.gd.a(Unknown Source)
    at com.ibm.db2.jcc.am.gd.a(Unknown Source)
    at com.ibm.db2.jcc.am.gd.a(Unknown Source)
    at com.ibm.db2.jcc.am.yo.c(Unknown Source)
    at com.ibm.db2.jcc.am.yo.d(Unknown Source)
    at com.ibm.db2.jcc.am.yo.b(Unknown Source)
    at com.ibm.db2.jcc.t4.bb.i(Unknown Source)
    at com.ibm.db2.jcc.t4.bb.c(Unknown Source)
    at com.ibm.db2.jcc.t4.p.b(Unknown Source)
    at com.ibm.db2.jcc.t4.vb.h(Unknown Source)
    at com.ibm.db2.jcc.am.yo.hb(Unknown Source)
    at com.ibm.db2.jcc.am.yo.a(Unknown Source)
    at com.ibm.db2.jcc.am.yo.e(Unknown Source)
    at com.ibm.db2.jcc.am.yo.execute(Unknown Source)
    at groovy.sql.Sql.execute(Sql.java:2248)
    at groovy.sql.Sql$execute.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at QueryHdfs.run(QueryHdfs.groovy:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
    at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
    at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
    at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:407)
    at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at QueryHdfs.main(QueryHdfs.groovy)
:QueryHdfs FAILED
```

**Comment by pregazzoni** [comment]
Added simple check to show data still there after drop table via commit 4a2a9de
