### ISSUE TITLE
Call Ambari Service Check: Exception in thread "main" groovyx.net.http.HttpResponseException: Forbidden

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#74]
HdfsServiceCheck is failing on basic clusters:

```
snowch$ cat build/test/Ambari-HdfsServiceCheck.txt 
:compileJava UP-TO-DATE
:compileGroovy
:processResources UP-TO-DATE
:classes
:HdfsServiceCheck

Get cluster info: 200

Cluster name is: csnow_cluster2

Call Ambari Service Check: Exception in thread "main" groovyx.net.http.HttpResponseException: Forbidden
    at groovyx.net.http.RESTClient.defaultFailureHandler(RESTClient.java:263)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
        ...
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at HdfsServiceCheck.main(HdfsServiceCheck.groovy)
:HdfsServiceCheck FAILED
```

I can share credentials if that will help to diagnose the issue.

**Comment by pregazzoni** [comment]
Chris, for service check the ambari user need to admin role to be able to do service check. standard user are basically read only users.

**Comment by pregazzoni** [comment]
Got access to your cluster and indeed user does not have "admin" role.

Need to see how to handle such case to exit more gracefully or skip if that is the case.

**Comment by snowch** [comment]
Cool. Thanks Pierre.

**Comment by pregazzoni** [comment]
Added some code to now list privileges the user has in ambari. The tests now will run successfully regardless of privilege but just exit if you don't have the right one, for example:

```
:HdfsServiceCheck

You don't have CLUSTER OPERATE privilege to run service check.
You have the following privileges: [CLUSTER.READ, VIEW.USE]

BUILD SUCCESSFUL

Total time: 5.123 secs
```

We should chat if we want to put this code at higher level potentially. Right now only HdfsServiceCheck test will do this check.

**Comment by snowch** [comment]
This makes sense. Thanks Pierre!
