### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#90]
```
DownloadCertificatesException in thread "HandshakeCompletedNotify-Thread" java.lang.UnsupportedOperationException
       at java.util.Collections$UnmodifiableCollection.addAll(Unknown Source)
       at org.codehaus.groovy.runtime.DefaultGroovyMethods.addAll(DefaultGroovyMethods.java:4440)
       at org.codehaus.groovy.runtime.dgm$4.doMethodInvoke(Unknown Source)
       at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.invoke(PojoMetaMethodSite.java:51)
       at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
       at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
       at build_af1jjpzejainum6xqr1lerv70$_run_closure3$_closure27$_closure28.doCall(C:\Big_Data\BigInsights\GitSampl       es\biginsight-examples\build.gradle:87)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
       at java.lang.reflect.Method.invoke(Unknown Source)
       at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
       at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
       at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
       at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
       at groovy.lang.Closure.call(Closure.java:426)
       at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:53)
       at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:105)
       at com.sun.proxy.$Proxy54.handshakeCompleted(Unknown Source)
       at sun.security.ssl.SSLSocketImpl$NotifyHandshakeThread$1.run(Unknown Source)
       at sun.security.ssl.SSLSocketImpl$NotifyHandshakeThread$1.run(Unknown Source)
       at java.security.AccessController.doPrivileged(Native Method)
       at sun.security.ssl.SSLSocketImpl$NotifyHandshakeThread.run(Unknown Source)
```

**Comment by snowch** [comment]
cc @cyborg7
